# Generated by Django 5.0.3 on 2024-03-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoría',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='título',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
