# Generated by Django 5.0.3 on 2024-03-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0004_alter_producto_categoria_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default='Sin edad', max_length=3)),
                ('nota', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
